Домашку сделал
SviatlanaMartsinkevich/Lesson6 pull request #1
Opened 2021-12-06 18:41 UTC by SviatlanaMartsinkevich

2021-12-13 12:26 UTC, wildpioneer requested changes

2021-12-13 12:26 UTC, wildpioneer commented on src/test/java/tests/HomeWork.java
> +
Придерживайся единообразия форматирования - если используешь одну пустую строку для разделения блоков - то так и используй

2021-12-13 12:26 UTC, wildpioneer commented on src/test/java/tests/HomeWork.java
> +        driver.close();
Зачем close?

2021-12-13 12:26 UTC, wildpioneer commented on src/test/java/tests/HomeWork.java
> +
Не оставляй пустых строк в конце метода, это создает впечатление, что ты что-то забыла добавить

2021-12-13 12:26 UTC, wildpioneer commented on src/test/java/tests/HomeWork3.java
> +
Аннотации размещаются сразу перед методом

2021-12-13 12:26 UTC, wildpioneer commented on src/test/java/tests/HomeWork3.java
> +        String executeNumberOfBoards = "53";
Ожидаемые результаты лучше инициализировать в начале метода, чтобы легче было менять

2022-01-08 14:16 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/HomeWork.java
> +
Ок, поняла

2022-01-08 14:16 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/HomeWork.java
> +        driver.close();
убрала

2022-01-08 14:16 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/HomeWork.java
> +
Ок

2022-01-08 14:16 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/HomeWork3.java
> +
Ок, поняла

2022-01-08 14:16 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/HomeWork3.java
> +        String executeNumberOfBoards = "53";
Ок

2022-01-17 11:33 UTC, closed without merging