Готовое дз
SviatlanaMartsinkevich/Lesson6 pull request #5
Opened 2022-01-15 22:19 UTC by SviatlanaMartsinkevich

2022-01-17 11:32 UTC, wildpioneer requested changes

2022-01-17 11:32 UTC, wildpioneer commented on src/test/java/tests/WaitsTest.java
> +        Assert.assertEquals(text.getText(), "Hello World!");
Проверка не совсем корректная

2022-01-17 11:32 UTC, wildpioneer commented on src/test/java/tests/JSTests.java
> +        javascriptExecutor.executeScript("window.scrollBy(0,4500)");
А если высота страницы измениться?

2022-01-22 22:00 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/WaitsTest.java
> +        Assert.assertEquals(text.getText(), "Hello World!");
исправила

2022-01-22 22:10 UTC, SviatlanaMartsinkevich commented on src/test/java/tests/JSTests.java
> +        javascriptExecutor.executeScript("window.scrollBy(0,4500)");
исправила

2022-01-31 11:26 UTC, wildpioneer commented
Проверено

2022-01-31 11:26 UTC, closed without merging